{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arashivision.sdk",
    "module": "sdk-bridge",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.arashivision.sdk",
          "module": "sdk-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "verticalBridge-metadata-2.2.0.jar",
          "url": "sdk-bridge-2.2.0.jar",
          "size": 11524,
          "sha512": "79524cff59695effc20bfd0fc202444b86914224a813668ba53991192332d5cdac3c606623db09b6f17239d329ae8071ecf41ed12e511390ac78f0d33e129f15",
          "sha256": "71bc52f16d61f168c89826ee4e2a4c35242880640327eb6221d3727a8801e9a3",
          "sha1": "112357505626216100f2d74292da9fd47f6c0ae5",
          "md5": "e158f6a8d43572101e70470735196810"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "verticalBridge-kotlin-2.2.0-sources.jar",
          "url": "sdk-bridge-2.2.0-sources.jar",
          "size": 8106,
          "sha512": "bf5715da1b70ab5921e733851d3957a47c204cf754474ff556c6e5c6a2edfea1ef112543bfd04f39962119ca72a0f0f7fd68370b31326ec3f09ae7a731532676",
          "sha256": "6ba3336c9dc605bfd702793fc4febc815c7afb9b2e19004d8a4f965e01c71558",
          "sha1": "550d3315bf45d931814178029f71780a8a64d486",
          "md5": "ff1634c5ef58fbd5e2f921c1d33a908c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-bridge-android/2.2.0/sdk-bridge-android-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-bridge-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-bridge-android/2.2.0/sdk-bridge-android-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-bridge-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-bridge-android/2.2.0/sdk-bridge-android-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-bridge-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-bridge-iosarm64/2.2.0/sdk-bridge-iosarm64-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-bridge-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-bridge-iosarm64/2.2.0/sdk-bridge-iosarm64-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-bridge-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-bridge-iosarm64/2.2.0/sdk-bridge-iosarm64-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-bridge-iosarm64",
        "version": "2.2.0"
      }
    }
  ]
}
