{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arashivision.sdk",
    "module": "sdk-camera",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.arashivision.inskmp",
          "module": "minicamera",
          "version": {
            "requires": "1.2310.13-feature-tob-2.1.5-20260904101959"
          }
        },
        {
          "group": "com.arashivision.sdk",
          "module": "sdk-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.arashivision.sdk",
          "module": "sdk-bridge",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "verticalCamera-metadata-2.2.0.jar",
          "url": "sdk-camera-2.2.0.jar",
          "size": 212753,
          "sha512": "0c5214952d959c8ae130cb4f6a0ad25894c061fce01a57defb79336022fecfa98c0612b75a788f8d587f6abd47d0e1e073c4b645e5141003adca7b398d350952",
          "sha256": "a7a7970b9442a0c2e3d7e3887a4a3b9213dcd1306a5f0d80a6fe576481f9e2fd",
          "sha1": "ae61f7de4f9cade0a6b54909f4d5e81383a83ef6",
          "md5": "0babf7c3b9815280baa9313668b31744"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "verticalCamera-kotlin-2.2.0-sources.jar",
          "url": "sdk-camera-2.2.0-sources.jar",
          "size": 272559,
          "sha512": "495f3e41068631090b5f04054f8ffbff1bd30d57d6a5321ed6f235f2b2d8aec194611db57dd4dfbda57a893821b8d5bcd84f564e85b679d17ad6dbbab82aef23",
          "sha256": "3390458f7d013354334c497add04fce0dccfcfe82bb62ef3d8bdc34bede8bf52",
          "sha1": "9532dd078a951748f2bcd4ebe7dcd55eef64685b",
          "md5": "81cea0eab6d2249a3a5b01d54e10038a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-camera-android/2.2.0/sdk-camera-android-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-camera-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-camera-android/2.2.0/sdk-camera-android-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-camera-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-camera-android/2.2.0/sdk-camera-android-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-camera-android",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-camera-iosarm64/2.2.0/sdk-camera-iosarm64-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-camera-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-camera-iosarm64/2.2.0/sdk-camera-iosarm64-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-camera-iosarm64",
        "version": "2.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-camera-iosarm64/2.2.0/sdk-camera-iosarm64-2.2.0.module",
        "group": "com.arashivision.sdk",
        "module": "sdk-camera-iosarm64",
        "version": "2.2.0"
      }
    }
  ]
}
